# Generated by Django 5.2.7 on 2026-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("contact", models.CharField(max_length=15)),
            ],
        ),
    ]
