# Generated by Django 5.2.7 on 2026-05-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="students.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date", "subject")},
        ),
    ]
